# AntiCheat Configuration File

# ============================
#         AUTO TOTEM
# ============================
# AntiCheat AutoTotem Configuration

autototem:
  # Minimum reaction time in milliseconds for totem usage to be considered valid
  minReactionTime: 500

  # Maximum number of totem uses allowed within a certain time frame (in milliseconds)
  maxTotemUsesPerTimeFrame: 3
  totemTimeFrame: 5000

  # Penalty system for suspicious activity
  violationThresholds:
    warning: 3        # Number of violations before a warning is given
    kick: 5           # Number of violations before player is kicked
    ban: 10           # Number of violations before player is banned

  # Messages to send to players
  messages:
    warning: "&f&l[VoidAntiCheat] &cSuspicious totem usage detected! Slow down!"
    kick: "&cYou have been kicked for using AutoTotem hacks."
    ban: "&cYou have been banned for AutoTotem exploits."

  # Admin notifications
  notifyAdmins: true
  adminNotificationMessage: "&f&l[VoidAntiCheat] %player% has been flagged for AutoTotem abuse."

  # Debug mode to log additional details for plugin debugging
  debug: false


# ============================
#        Anti-Killaura
# ============================
# Configuration for AntiKillaura

anti-killaura:

  # Max angle for direction change (degrees)
  max-attack-angle: 45

  # Max speed the player can move (adjust based on your needs)
  max-movement-speed: 1.3

  # Minimum time between attacks in milliseconds
  minimum-attack-interval: 150

  kick-message: "Killaura detected! You have been kicked."
  logging:
    # Whether to log detections in the console
    log-detections: true

    # Whether to notify admins when a player is kicked
    notify-admins: true


# ============================
#        Auto-Clicker
# ============================
#Anti auto-clicker hack config

# Click time threshold in milliseconds for AutoClicker detection
clickTimeThreshold: 100

# Maximum clicks allowed per second
maxClicksPerSecond: 10


# ============================
#            X-Ray
# ============================
# XRay Detection config

xray:

  # Time window (in milliseconds) to analyze mining patterns (default: 60 seconds)
  timeWindow: 180000

  # Minimum distance (in blocks) between mined valuable ores to trigger suspicion
  minDistanceBetweenOres: 3.5

  # Maximum number of ores mined in close proximity before flagging as suspicious
  maxOresInProximity: 5

  # List of ores considered valuable for XRay detection
  valuableOres:
    - DIAMOND_ORE
    - EMERALD_ORE
    - GOLD_ORE
    - ANCIENT_DEBRIS
    #  add more if necessary


# ============================
#           No-Fall
# ============================
# NoFall AntiCheat Configuration

# The maximum fall distance a player can fall before triggering NoFall detection.
maxFallDistance: 4.0

# The time after a fall that NoFall detection resets, in milliseconds.
noFallResetTime: 5000

# The expected fall damage when no hacks are being used.
expectedFallDamage: 2.0


# ============================
#           No-Fall
# ============================
# Anti fly hack config

# Threshold for fly detection (in milliseconds)
flyDetectionThreshold: 5000

# fly is still on progress


# ============================
#          Violations
# ============================
# Violation thresholds for actions
violationThresholds:
  # Number of violations before kicking the player
  kick: 3

  # Number of violations before banning the player
  ban: 5

# Notification message format for admins
notifyMessage: "&f&l[VoidAntiCheat] &e%player% &chas been flagged for %reason%"


# More improvement well come soon and Thanks fo Downloading This plugin