# AntiCheat Configuration File

# Anti Speed hack config
maxSpeed: 1.3 # Maximum speed a player can move (in blocks per second)

# Anti fly hack config
flyDetectionThreshold: 5000 # Threshold for fly detection (in milliseconds)

#Anti auto-clicker hack config
clickTimeThreshold: 150 #time old for click detection (in milliseconds)
maxClicksPerSecond: 15 #maximum clicks allowed per second

# Anti NoFall hack config
# Maximum fall distance before triggering no-fall detection
maxFallDistance: 6.0  # Height above which fall damage should occur
# Minimum damage expected from falls to avoid false positives
expectedFallDamage: 1.0  # Adjust this based on testing fall damage
# Time (in milliseconds) to reset no-fall detection (for repeated checks)
noFallResetTime: 3000  # 5 seconds

# XRay Detection config
xray:
  timeWindow: 180000  # Time window (in milliseconds) to analyze mining patterns (default: 60 seconds)
  minDistanceBetweenOres: 3.5  # Minimum distance (in blocks) between mined valuable ores to trigger suspicion
  maxOresInProximity: 5  # Maximum number of ores mined in close proximity before flagging as suspicious
  valuableOres:  # List of ores considered valuable for XRay detection
    - DIAMOND_ORE
    - EMERALD_ORE
    - GOLD_ORE
    - ANCIENT_DEBRIS
   #  add more if necessary

# Anti Killaura hack config
killaura:
  attackSpeedThreshold: 250     # Minimum time between attacks (milliseconds)
  maxAttackAngle: 90.0          # Maximum allowed attack angle
  multiHitThreshold: 300        # Time threshold for multiple entity hits (milliseconds)
  maxReach: 4.6                 # Maximum allowed reach distance (blocks)
  maxYawDifference: 240.0       # Maximum allowed yaw difference for head movement

# Violation thresholds for actions
violationThresholds:
  kick: 3  # Number of violations before kicking the player
  ban: 5   # Number of violations before banning the player

# Notification message format for admins
notifyMessage: "&c%player% has been flagged for %reason%"
