# AntiCheat Configuration File

# ============================
#         AUTO TOTEM
# ============================
# AntiCheat Configuration

# Configuration for AutoTotem detection
AutoTotem:
  # Time in milliseconds to check for rapid totem usage
  rapidUsageThreshold: 50

  # Message to display when a violation is triggered
  violationMessage: "AutoTotem hack suspected! Please stop using exploits."

  # List of players exempt from AutoTotem checks (for testing purposes)
  exemptPlayers:
    - "playerUUID1" # Replace with actual player UUIDs
    - "playerUUID2"

# General settings
general:
  # Enable or disable the AutoTotem detection feature
  enableAutoTotemDetection: true

  # Log violations to console
  logViolations: true

  # Admin notification settings
  adminNotification:
    # Enable or disable admin notifications
    enabled: true

    # Message to notify admins of violations
    notificationMessage: "Player {player} has triggered a violation: {violation}"

# Violation handling
violationHandling:
  # Action to take when a violation is detected
  actions:
    - action: "kick"
      message: "You have been kicked for using hacks!"
      # Optional: specify a cooldown time before the player can rejoin
      cooldown: 600 # in seconds (10 minutes)

    - action: "ban"
      duration: 86400 # in seconds (1 day)
      reason: "Hacking - AutoTotem usage detected"



# ============================
#        Anti-Killaura
# ============================
# Configuration for Anti-Killaura

antiKillaura:
  # "true" means the Anti-Killaura is Enabled
  # "false" means the Anti-Killaura is disabled
  enabled: true

  # weapons that are is used for Killaura
  allowedWeapons:
    - DIAMOND_SWORD
    - WOODEN_SWORD
    - STONE_SWORD
    - IRON_SWORD
    - NETHERITE_SWORD
    - AIR

  clickThreshold: 300  # in milliseconds

 # message that will send when Killaura is detected
  violationMessage: "&cCheats are not allowed. &eKillaura &cdetected!"

  violationActions:
    - "notify"  # Actions like notify, kick, ban, log can be configured
  # - "kick"   # Add more actions like this if needed


# ============================
#        Auto-Clicker
# ============================
#Anti auto-clicker hack config

# Click time threshold in milliseconds for AutoClicker detection
clickTimeThreshold: 100

# Maximum clicks allowed per second
maxClicksPerSecond: 10


# ============================
#            X-Ray
# ============================
# XRay Detection config

xray:

  # Time window (in milliseconds) to analyze mining patterns (default: 60 seconds)
  timeWindow: 180000

  # Minimum distance (in blocks) between mined valuable ores to trigger suspicion
  minDistanceBetweenOres: 3.5

  # Maximum number of ores mined in close proximity before flagging as suspicious
  maxOresInProximity: 5

  # List of ores considered valuable for XRay detection
  valuableOres:
    - DIAMOND_ORE
    - EMERALD_ORE
    - GOLD_ORE
    - ANCIENT_DEBRIS
    #  add more if necessary


# ============================
#           No-Fall
# ============================
# NoFall AntiCheat Configuration

# The maximum fall distance a player can fall before triggering NoFall detection.
maxFallDistance: 4.0

# The time after a fall that NoFall detection resets, in milliseconds.
noFallResetTime: 5000

# The expected fall damage when no hacks are being used.
expectedFallDamage: 2.0


# ============================
#           No-Fall
# ============================
# Anti fly hack config

# Threshold for fly detection (in milliseconds)
flyDetectionThreshold: 5000

# fly is still on progress


# ============================
#          Violations
# ============================
# Violation thresholds for actions
violationThresholds:
  # Number of violations before kicking the player
  kick: 3

  # Number of violations before banning the player
  ban: 5

# Notification message format for admins
notifyMessage: "&c%player% has been flagged for %reason%"


# More improvement well come soon and Thanks fo Downloading This plugin