# AntiCheat Configuration File

# ============================
#         AUTO TOTEM
# ============================
# AntiCheat AutoTotem Configuration

autototem:

  # Minimum time between using totems (in milliseconds)
  minReactionTime: 500

  # Max totem uses in a given time frame
  maxTotemUsesPerTimeFrame: 3
  # Time frame in milliseconds to track usage
  totemTimeFrame: 5000

  violationThresholds:

    warning: 3 # warns the player
    kick: 5 # kicks the player
    ban: 10 # bans the player

  messages:
    warning: '&f&l[VoidAntiCheat] &eWarning: Suspicious totem usage detected!'
    kick: '&cYou have been kicked for using totems too fast.'
    ban: '&4You have been banned for using totems too fast.'

  # if sets to "true" then the admin/op gets a message
  notifyAdmins: true
  debug: false # gives console message

  # Admin/OP gets a message
  adminNotificationMessage: '&c[AntiTotem] %player% has been %action% for totem abuse.'



# ============================
#        Anti-Killaura
# ============================
# Configuration for Anti-Killaura

anti-killaura:

  # Attack frequency detection
  # Max attacks per second before detection
  max-attack-frequency: 4.0

  # Min time between attacks in milliseconds
  minimum-attack-interval: 200

  # Aim detection
  # Default is "60". it's important to set this properly
  # Max angle difference between player's aim and target
  max-aim-angle: 60.0

  # Warnings and kicking
  # Number of warnings before the player is kicked
  max-warnings: 3
  #warning message
  warning-message: '&f&l[VoidANtiCheat] &cWarning: Suspicious behavior detected! You have &d{warnings_left} &cwarnings left before being kicked.'

  # Kick message
  kick-message: '&cYou have been kicked for suspected Killaura usage!'

  # Logging
  logging:
    notify-admins: true # Notify admins when Killaura is detected
    log-to-console: false # Log detection in the console


# ============================
#        Auto-Clicker
# ============================
#Anti auto-clicker hack config

# Click time threshold in milliseconds for AutoClicker detection
clickTimeThreshold: 100

# Maximum clicks allowed per second
maxClicksPerSecond: 10


# ============================
#            X-Ray
# ============================
# XRay Detection config

xray:

  # Time window (in milliseconds) to analyze mining patterns (default: 60 seconds)
  timeWindow: 180000

  # Minimum distance (in blocks) between mined valuable ores to trigger suspicion
  minDistanceBetweenOres: 3.5

  # Maximum number of ores mined in close proximity before flagging as suspicious
  maxOresInProximity: 5

  # List of ores considered valuable for XRay detection
  valuableOres:
    - DIAMOND_ORE
    - EMERALD_ORE
    - GOLD_ORE
    - ANCIENT_DEBRIS
    #  add more if necessary


# ============================
#           No-Fall
# ============================
# NoFall AntiCheat Configuration

# The maximum fall distance a player can fall before triggering NoFall detection.
maxFallDistance: 4.0

# The time after a fall that NoFall detection resets, in milliseconds.
noFallResetTime: 5000

# The expected fall damage when no hacks are being used.
expectedFallDamage: 2.0


# ============================
#           No-Fall
# ============================
# Anti fly hack config

# Threshold for fly detection (in milliseconds)
flyDetectionThreshold: 5000

# fly is still on progress


# ============================
#          Violations
# ============================
# Violation thresholds for actions
violationThresholds:
  # Number of violations before kicking the player
  kick: 3

  # Number of violations before banning the player
  ban: 5

# Notification message format for admins
notifyMessage: "&f&l[VoidAntiCheat] &e%player% &chas been flagged for %reason%"


# More improvement well come soon and Thanks fo Downloading This plugin